# Copyright 2021 Ioannis Papadopoulos
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.7'

services:
    backend:
        build:
            context: ./backend
            dockerfile: backend.Dockerfile
        volumes:
            - ./backend:/app/backend
        restart: always
        privileged: true
        ports:
            - "8000:8000"
        expose:
            - "8000"
        stdin_open: true
        tty: true
        environment:
            - SECRET_KEY=${SECRET_KEY}
        command: >
            sh -c "python3 manage.py makemigrations
            && python3 manage.py migrate
            && python3 manage.py runserver 0.0.0.0:8000"

    collector:
        build:
            context: ./package_info_collector
            dockerfile: collector.Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - backend
        privileged: true
        stdin_open: true
        tty: true
        network_mode: host
