version: '3.7'

services:
    backend:
        build:
            context: ./backend
            dockerfile: backend.Dockerfile
        volumes:
            - ./backend:/app/backend
        restart: always
        privileged: true
        ports:
            - "8000:8000"
        expose:
            - "8000"
        stdin_open: true
        tty: true
        environment:
            - SECRET_KEY=${SECRET_KEY}
        # depends_on: 
        #     - db
        #     - redis
        # links:
        #     - db
        command: >
            sh -c "python3 manage.py makemigrations
            && python3 manage.py migrate
            && python3 manage.py runserver 0.0.0.0:8000"