# Generated by Django 3.2.5 on 2021-07-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('distro', models.CharField(choices=[('Ubuntu', 'Ubuntu'), ('Debian', 'Debian'), ('Fedora', 'Fedora')], max_length=50)),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('license', models.CharField(blank=True, default='', max_length=50)),
                ('maintainer', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('homepage', models.URLField(blank=True, default='')),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'distro')},
            },
        ),
        migrations.CreateModel(
            name='Package_Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('architecture', models.CharField(choices=[('amd64', 'amd64'), ('i386', 'i386'), ('amd64 i386', 'amd64 i386')], max_length=20)),
                ('swhid', models.CharField(max_length=100)),
                ('swhid_exists', models.BooleanField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package')),
            ],
        ),
    ]
