# Generated by Django 3.2.5 on 2022-02-01 02:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('distro', models.CharField(max_length=50)),
                ('type', models.CharField(default='', max_length=20)),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('license', models.CharField(blank=True, default='', max_length=200)),
                ('maintainer', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('homepage', models.URLField(blank=True, default='')),
                ('repo_URL', models.URLField(blank=True, default='')),
            ],
            options={
                'unique_together': {('name', 'distro')},
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('architecture', models.CharField(max_length=50)),
                ('swhid', models.CharField(blank=True, default='', max_length=100)),
                ('swhid_exists', models.BooleanField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.00095)])),
                ('binary_URL', models.URLField(blank=True, default='')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.package')),
            ],
            options={
                'unique_together': {('package', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pkg_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.packageversion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pkg_version_id', 'user_id')},
            },
        ),
    ]
