# Generated by Django 3.2.5 on 2021-07-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('architecture', models.CharField(choices=[('amd64', 'amd64'), ('i386', 'i386'), ('amd64 i386', 'amd64 i386')], max_length=20)),
                ('swhid', models.CharField(max_length=100)),
                ('swhid_exists', models.BooleanField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.package')),
            ],
        ),
        migrations.DeleteModel(
            name='Package_Version',
        ),
    ]
