# Generated by Django 3.2.5 on 2021-07-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210725_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='swhid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
