# Generated by Django 3.2.5 on 2021-07-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_packageversion_swhid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packageversion',
            unique_together={('package', 'version', 'architecture')},
        ),
    ]
