# Generated by Django 3.2.5 on 2022-02-05 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='packageversion',
            options={'ordering': ['-version']},
        ),
    ]
