# Generated by Django 3.2.5 on 2021-07-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_packageversion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='distro',
            field=models.CharField(max_length=50),
        ),
    ]
