# Generated by Django 3.2.5 on 2022-02-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_package_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='license',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
