# Generated by Django 3.2.5 on 2021-07-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_package_distro'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packageversion',
            unique_together={('package', 'version')},
        ),
    ]
