# Generated by Django 3.2.5 on 2022-01-06 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_packageversion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='size',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
