# Generated by Django 3.2.5 on 2022-02-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220206_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
    ]
