# Generated by Django 3.2.5 on 2022-01-08 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_packageversion_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='size',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-07)]),
        ),
    ]
