# Generated by Django 3.2.5 on 2022-01-18 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_packageversion_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='repo_URL',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='binary_URL',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='architecture',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='size',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.00095)]),
        ),
    ]
