# Generated by Django 3.2.5 on 2022-01-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220118_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='package',
            name='license',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='maintainer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='section',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='architecture',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
