# Generated by Django 3.2.5 on 2022-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220129_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
