# Generated by Django 3.2.5 on 2022-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='section',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
